### ISSUE TITLE
Cluster support?

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-redis#2]
Does this role support creating a cluster?

**Comment by robertdebock** [comment]
Hi @bbaassssiiee, not tested and reading [some documentation of Redis clustering](https://redis.io/topics/cluster-tutorial), not it does not.

Can I encourage your to make a PR? :innocent:

**Comment by bbaassssiiee** [comment]
No, I'm looking on Galaxy for yet another Redis role. One suitable for a hi-spec air-gapped RHEL environment.
